### ISSUE TITLE
globals

### ISSUE THREAD

**Issue by tehn** [monome/norns#557]
see #425 

- [x] reset globals created by scripts between loads - fixed by https://github.com/monome/norns/pull/436
- [x] clean up system globals #559
- [x] consider adding underscores to system globals
- [x] consider putting c functions into a table - see https://github.com/monome/norns/issues/425#issuecomment-397030353
- [ ] disable overwriting system globals - see https://github.com/monome/norns/pull/436#issuecomment-403100830 @pq 
- [ ] protect some specific tables (ie `engine`) #912 @pq

**Comment by pq** [comment]
> @tehn: do we have a sense for what globals we want to protect and what we want to preserve across scripts?

this is related to the general cleanup task i guess.  there may not actually be much left to protect / restore when norns is less leaky...
