### ISSUE TITLE
doc updates for 2.0.0

### ISSUE THREAD

**Issue by pq** [monome/norns#720]
punch list for 2.0.0, migrated from various conversations.

  - [ ] improve luadocs #455 
  - [ ] review (and repair) all the norns studies #721 
  - [ ] create a "programmers reference" doc #717
  - [ ] update main user docs for 2.0.0 #718
  - [ ] create a "2.0 transition" doc #719
  - [ ] update the `README` #433 

/cc @tehn @okyeron @jasonw22

**Comment by jasonw22** [comment]
Any thoughts about whether it makes sense to tackle these in any particular sequence?

**Comment by jasonw22** [comment]
Is #105 related to this as well?

**Comment by okyeron** [comment]
Making a note while it's fresh in my brain:

Need documentation of where everything goes when creating a norns engine - and also when that engine uses a non-installed Ugen (or quark?).

My process so far:
- compile ugen on norns ([recent reference from zebra](https://llllllll.co/t/norns-ideas/17625/197?u=okyeron))
- copy SC files (.sc, .so,  .cpp) to `~/.local/share/SuperCollider/Extensions`
- copy norns engine file to `~/norns/sc/engines` 
- run ./crone.sh to check engine for compile errors
- run ./stop.sh and ./start.sh

**Comment by catfact** [comment]
can we update / close this (and child issues?)

**Comment by simonvanderveldt** [comment]
I think most of these are covered, not sure about the 1st and 5th item.
@pq might know more about those.
