### ISSUE TITLE
review (and repair) all the norns studies for 2.0.0

### ISSUE THREAD

**Issue by pq** [monome/norns#721]
- [ ] https://github.com/monome/docs/blob/master/docs/norns/study-1.md
- [ ] https://github.com/monome/docs/blob/master/docs/norns/study-2.md
- [ ] https://github.com/monome/docs/blob/master/docs/norns/study-3.md
- [ ] https://github.com/monome/docs/blob/master/docs/norns/study-4.md
- [ ] https://github.com/monome/docs/blob/master/docs/norns/study-5.md

**Comment by pq** [comment]
See also https://github.com/monome/docs/issues/64.

**Comment by jasonw22** [comment]
Is 2.0 close enough to stable to tackle this one? Can someone point me to install instructions?

**Comment by catfact** [comment]
@jasonw22 see here https://github.com/monome/norns/pull/676

top post has some instructions, further down has some Q/A

**Comment by tehn** [comment]
the installer will get you in a position to pull the repos and recompile. there have already been changes to `norns` so be sure to `git pull` then `./waf`

the "official" public beta will be next thursday (when i get back from travel so i can be present)

**Comment by okyeron** [comment]
FWIW - I did study 4 here: https://github.com/monome/docs/pull/69 so don't work on that one :)

**Comment by okyeron** [comment]
Request from lines: "Add a link to the norns docs from each study page" - specifically to the [not-on-device docs](url
https://monome.github.io/norns/doc/)

**Comment by simonvanderveldt** [comment]
@pq I think this one is done, right?
