### ISSUE TITLE
clean up softcut buffer management

### ISSUE THREAD

**Issue by catfact** [monome/norns#934]
audio buffer save and load should be handled by main or dedicated worker thread in `crone`.
presently, buffer operations are performed directly in OSC handler, 
which is bad because it blocks the handling of other commands.

 - [ ] request class (timestamp, filename)
 - [x] worker thread (or main loop) and work Q (abstraction?)
 - [ ] completion handler (lua)
 - [ ] test / example script

while we're at it, some improvments to buffer read/write routines are in order:
 - [x] read/write larger blocks
 - [x] check libsndfile wrap/clip behavior for f32->s24 OOB values

**Comment by catfact** [comment]
* buffer management fixes

audio buffer save and load should be handled by main or dedicated worker thread in `crone`. (
presently, buffer operations are performed directly in OSC handler, 
which is bad because it blocks the handling of other commands.

** TODO request class (timestamp, filename)
** TODO worker thread (or main loop) and work Q (abstraction?)
** TODO completion handler (lua)
** TODO test / example script

while we're at it, some improvments to buffer read/write routines are in order:

*** TODO read/write larger blocks
*** TODO check libsndfile wrap/clip behavior for f32->s24 OOB values

**Comment by catfact** [comment]
i'm calling this done for now. disk workers seem to be doing the job. 

if we want callbacks to lua on job completion, that's pretty easy to add, but maybe i'll wait for a use case.
